/// Flutter icons Battle2
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Battle2
///      fonts:
///       - asset: fonts/Battle2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Battle2 {
  Battle2._();

  static const _kFontFam = 'Battle2';
  static const String? _kFontPkg = null;

  static const IconData battle2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
