enum FeedNovelMode {
  MY_NOVELS,
  SELECTED_WRITERS_NOVELS,
  FAVORITE_WRITERS_NOVELS,
  FRIENDS_WRITERS_NOVELS,
  SELECTED_NOVELS,
  SEARCHED_BY_MULTIPLE_NOVELS,
  ALL_NOVELS,
}

enum ProfileMode{
  MYSELF,
  OTHER
}

enum MyHomeMode{
  EDIT_PROFILE,
  NORMAL_PROFILE
}

enum MyProfileSettingMenu{
  LOG_OUT,
  EDIT_PROFILE,
  NORMAL_PROFILE,
  // FINISH_EDIT_PROFILE,
}

enum FeedWriterMode{
  All_Writer,
  SELECTED_WRITER,
}

enum GenreDropDownButtonMode{
  WRITING_GENRE_DROP_DOWN,
  FEED_GENRE_DROP_DOWN,
  WRITER_GENRE_DROP_DOWN,
  CLEAR
}